project:
  title: "googlie_quarto"
  type: website

website:
  title: "Googlie Quarto"
  site-url: https://josephlara.github.io/googlie_quarto/
  navbar: false

format:
  html:
    toc: true
    theme: default
