name: Test Quarto Report

on:
  schedule:
    - cron: '8 * * * *'  # every hour on the hourqua
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      GSHEET_AUTH_JSON: .github/gsheet.json
      GSHEET_JSON: ${{ secrets.GSHEET_JSON }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          Rscript -e 'install.packages(c("quarto", "googlesheets4", "dplyr", "readr", "tidyverse"))'

      - name: Decode and save Google service account key
        run: |
          echo "$GSHEET_JSON" | base64 --decode > .github/gsheet.json

      - name: Render Quarto
        run: quarto render
