name: Publish Quarto Site

on:
  schedule:
    - cron: '0 * * * *'  # every hour at :00
  workflow_dispatch:
  
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
      QUARTO_PUB: gh-pages

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org")); install.packages(c("dplyr", "readr", "ggplo2", "googlesheets4", "gt"))'

      - name: Decode and save Google service account key
        run: |
          echo "$GSHEET_JSON" | base64 --decode > .github/gsheet.json

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Publish site to gh-pages
        run: |
          quarto publish gh-pages --no-browser --token ${{ secrets.GITHUB_TOKEN }}

