name: Publish Quarto Site

on:
  schedule:
    - cron: '20 * * * *'  # every hour at :06
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      GSHEET_JSON: ${{ secrets.GSHEET_JSON }}
      QUARTO_PUB: gh-pages

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("googlesheets4", "dplyr", "readr", "tidyverse"))'

      - name: Decode and save Google service account key
        run: |
          echo "$GSHEET_JSON" | base64 --decode > .github/gsheet.json

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Publish site to gh-pages
        run: |
          quarto publish gh-pages --no-browser --token ${{ secrets.GITHUB_TOKEN }}
