name: Test Quarto Report

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    env:
      GKEY_JSON: ${{ secrets.GSHEET_JSON }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          Rscript -e 'install.packages(c("quarto", "googlesheets4", "dplyr", "readr", "tidyverse"))'

      - name: Decode and save Google service account key
        run: |
          echo "$GKEY_JSON" | base64 --decode > gsheet.json

      - name: Render Quarto
        run: |
          Rscript -e 'googlesheets4::gs4_auth(path = "gsheet.json")'
          quarto render
